### PR TITLE
Fix/file names

### LINKED ISSUE #47: Modify plot filenames after slicing URL
When grabbing the plots from the external GH repo, the filenames are changed as they are taken from the URL. We should be passing the actual plot filename to the zip file method so filenames persist and users can identify which image is which.

### PR DESCRIPTION
**Pull request by acholyn**
Related to https://github.com/UCL/UKCORDEX-plot-explorer/issues/18
Closes https://github.com/UCL/UKCORDEX-plot-explorer/issues/47

### CODE REVIEW

File: src/components/Utils/downloadZip.js [hunk 1]
```diff
@@ -0,0 +1,40 @@
...
+        }
+        zip.file(filename, data, { binary: true });
+        count++;
+        if (count === downloads.length) {
+          zip.generateAsync({ type: "blob" }).then(function (content) {
+            saveAs(content, zipFilename);
+          });
+        }
+      });
+      return console.log("filenames have been mapped"); // function is unhappy without return
```
Comment (raquelalegre) [inline src/components/Utils/downloadZip.js]: How about `return (null);` or similar?

Comment (acholyn) [reply src/components/Utils/downloadZip.js]: seems that works, I've implemented it.

**Review by raquelalegre — APPROVED** [review]
Approving. Just made a small comment about returning null in a function, but functionality is there and seems ok!
