### PR TITLE
Fix/aesthetics

### LINKED ISSUE #49: Cosmetic changes
- [x] New plots need icons in the dropdown
- [x] Separation between the OptionsRow sections and the button and FigureRow sections when there are no warnings
- [x] "Annual" tag

### PR DESCRIPTION
**Pull request by acholyn**
Closes https://github.com/UCL/UKCORDEX-plot-explorer/issues/49

### CODE REVIEW

**Comment by raquelalegre** [comment]
Something odd is happening with the resolution dropdown. 

To reproduce one of this:
1. Choose one option in each dropdown, with the resolution being 12 km.
2. Add a second resolution
3. Try to add a third resolution 

Step 3 can't be completed because no more resolutions show, but they should.

To reproduce another one:
1. Choose one option in each dropdown, with the resolution not being 12 km
2. Add a second resolution

Step 2 shows only one option remaining (12 km) when it should show more

File: src/components/OptionsRow.js [hunk 1]
```diff
@@ -51,7 +51,7 @@ function OptionsRow({
 */
   return (
     <Container fluid>
-      <Row className="pt-4 opt-row">
+      <Row className="pt-4 mb-4">
```
Comment (raquelalegre) [inline src/components/OptionsRow.js:54]: This now also adds extra space when there is a warning. Is there a way where we have a consisten amount of space between the options row and the figure rows? I imagine the warning box has margin on top that we can delete?

File: src/components/DownloadButton.css [hunk 2]
```diff
@@ -3,8 +3,8 @@
 .downloadbtn,
 .downloadbtn a,
 .downloadbtn a:hover {
-  position: -webkit-sticky;
-  position: sticky;
+  /* position: -webkit-sticky;
+  position: sticky; */
```
Comment (raquelalegre) [inline src/components/DownloadButton.css]: Maybe delete?

**Review by raquelalegre — APPROVED** [review]
Approved with a minor comment on consistent space, and raised a problem with the resolution dropdown that can be dealt with at a separate PR.

**Comment by raquelalegre** [comment]
Created a new issue about the inconsistent behaviour of the resolution dropdown https://github.com/UCL/UKCORDEX-plot-explorer/issues/51
